### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by KMills245**

### CODE REVIEW

**Review by dealmeidavf — CHANGES_REQUESTED** [review]
Please merge the existing README in your branch before making changes to it.
Note what you are trying to change in the README file. I fiixed what was broken before. Did you see my pushes?

**Comment by KMills245** [comment]
I saw that after I pushed it! My apologies for the mistake

________________________________

**Review by dealmeidavf — CHANGES_REQUESTED** [review]
You are still trying to change the size of the figure in the readme file and the editing I did.

**Comment by KMills245** [comment]
Do I just need to close the pull request? I am updated with main so it will leave the readme unchanged

**Pull request closed without merging**
